language: go
sudo: false
go:
- 1.5
before_install:
- npm install
- npm run build
- pip install --user ruamel.yaml
script:
- npm test
- "./codecheck.sh -u"
- go test ./...
branches:
  only:
  - master
  - production
  - staging-alpha
before_deploy:
- export BUILD_INFO=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
# Extract any encrypted env vars and put them into the manifests/manifest-master.yml
- python deploy/travis-vars-to-manifest.py
# Download the go-bindata binary, which is necessary for the CF CLI
- go get -u github.com/jteeuwen/go-bindata/...
- export GOBINDATA_BIN=$(which go-bindata)
- export PATH=$GOBINDATA_BIN:$PATH
- echo $GOBINDATA_BIN
# Download the autopilot binary
- go get -u github.com/concourse/autopilot
- export GOAUTOPILOT_BIN=$(which autopilot)
- export PATH=$GOAUTOPILOT_BIN:$PATH
# Make sure we can execute the deploy script.
- chmod a+x deploy/travis_deploy.sh
# Download the CF CLI Soruce files
- export CLIPATH=$HOME/gopath/src/github.com/cloudfoundry/cli
- export GOPATH=$HOME/gopath/$CLIPATH/Godeps/_workspace:$HOME/gopath
- mkdir -p $CLIPATH
- git clone --branch v6.12.3 https://github.com/cloudfoundry/cli.git $CLIPATH
# Build the CF CLI
- chmod a+x deploy/prepare_deploy.sh
- deploy/prepare_deploy.sh
deploy:
- provider: script
  skip_cleanup: true
  script: deploy/travis_deploy.sh
  on:
    branch:
    - master
    - production
    - staging-alpha
env:
  global:
  - CF_API=https://api.cloud.gov
  - CF_ORGANIZATION=cf
  - CONSOLE_UAA_URL=https://uaa.cloud.gov/
  - CONSOLE_API_URL=https://api.cloud.gov/
  - CONSOLE_LOG_URL=https://loggregator.cloud.gov/
  - CONSOLE_LOGIN_URL=https://login.cloud.gov/
  - CONSOLE_HOSTNAME=http://localhost:9999/
  - CONSOLE_TEST_ORG_NAME=CF-DECK
  - CONSOLE_TEST_SPACE_NAME=testSpace01
  - CONSOLE_TEST_APP_NAME=testapp01
  - CONSOLE_TEST_HOST=testtestroute1
  - CONSOLE_TEST_DOMAIN=apps.cloud.gov
  - secure: xn/EXShpj51D9TTQgwrOj5H3c7gr41i+KnoOesfJDc1twY4reS8bWIBZU1zq2xaMsA8sus97Byk5MSXKifIzO5Gk6nyKzBo1z0HIXhpAVBy8RwNpLvUZrjrtz/24FmeQWs7McIfPZ92UWsGTI0BGVsSbIeAzeAkwIXb0/M1HUG4r7wgEOF+dlr3pYOtQBJ45wsst+n1RzUbWyHP7UPCcNHSrI7Q1y4odtK0MLMIozWBm5TbhpJnN4ylQCVPg2077Bsb5emg0G1K2Gfplhzvsu2+1BOekBHBsA4MJIPA1Y4dB2rkHeRvWgIyjg+w+wDyq0Kd4yP5Kku/N1U2b1llaOOLNABGYmfkteFgugHv73xfPoN2uLRIrWOpxywp+r/7qVDO8s5ZjjAGQfnFql53JBxD7/eAKH4sqaR5uW1uSpwpAmjaNAa7wcmgFKi0nyFovIBgbTH37M8nSDIS6/YfYYRiGMQA3piiUvBqVFpguSDrgup8/O8KsMn2SfPLvk7GG5bb8JOO0dWzXFuq1CWSzU4cIvcYfVkwmOKjpvKXYX1ebZz3T7i+ZL1fijQKFMlzpQGNPqHZJ/QwjH45G+Nw8Cz4waxP8l4C4ros5rIgR6CdYoRqfrhGMODum/JmoChM85hVbZbRw0AMJ+mRgprqDkru1AGSeBrxxSnwmX6eS0bs=
  - secure: GJ6iBRZ0NAw9d/RxA0BjyIRawDYUd5oVPRSEvmRWzxjw+eghBCKgp/K3RW7D6hbKUJTJ/A95Tm1cy74OgUffMkD5q5I6AJaf0LHp5rNSVP5Izu0ewbh95UE6WbFhytJjLu0Qsl0uW9v5/omG4Qm7odvvnWGO8yGDJpAbO+rMG1I09puy8n5QNESuUX0pwJKsQ1E/3uHwPfhFUacKl0bFHIEM8hLA9FWV5pl5p+cbx3fAU4U6hajB9Pur9zlRWb88nFOjrDE86RpA6Ihcu6qWERmOz441NWinUfGoLZruWp4YVhErZVp2KcOpMWyl5ObQ8Bu8JWyT9tGInyI9KPO+b5UI7i1jUkRJyQT2/snRdWcvYMWPe7gyQMz8VIogR/UUGOCBUGFm2+N03cb+UV8NxfSuR7IruX+8fWw0HvL02QYGWB1pTbebpdwn+V/ZO0+6DrOn62BVpxVqE8mNVS9Z2927GDsXRBA/C/KAHK6zaa1Vk5ADCDCFe3meysBp6BIWXKRDlnXgsomQzjAZ+Ri5us5zPWYQnIjvbJGUwXOpcFn7HiAQf0JzhvTb6s1F64Lr9yk82+rqtMSf5H3WW6yaJUirGtxlb1McD4BnsIH7F/C0ALJdZy35ZCKFhvFbGdsBeZGl6AYIuNqKz3r5U6gYycrRQ+/lGftVVRUTk90gR8A=
  - secure: mtat9B37f1xgoAgA5hxPO8vShP1wT7a9OWpDNo2W6sUhs65oFn6SoRe7/DU6QhnDV9jYn9SBpQ0K9K6VmvZbMiOwgn3XBuHW5UIQMG8ehGjxZ4DAZ3EtU/WQMsCAv9DfSH3RlP53v8goW2+KXxjefz8R0YR5KbiOK90/lg9zCYsv11KVu1etiLGvOBRHwDhV2Qayk67LMBLIf5mxGzKDA2Itqd03PB69tqz5sR4uyjxAcXWT+1+2oaiQtpBoD1ubEWUmQ5xSynJmI1/4BNSSeAhfjn405o70/ZO0l212bRBYlnQeIQCcjZUsWhNH1PYie+lavA6UngCfQEO7X7iS9NxGPWSzISy5kOYxntJKN/cVcX9QCb7QX/C+zJzjUU5paJLiRhRcojGQZXNpC+X8ALPuEMDRwyzVsBnqF+FZONb9ona/phqdMBawSzEZQGuGvI2+x1uLswYKv5iW0jJEhZ+MsSq+jRjUU6RnZtauX3QGZu6QYiaDc9McLof0YGenL95nl80UkbqvpNq3rVqw14rz4hPIZHiynUhJB6jY3wDQyiaBxhGkUiGx5SlxQWqME5/nGD5xYlj8ImNM0n7m21QS4WMxuRpRiAaVxfixCyKZxa5UEyEx/MDWVPnfurPRlNxeLl5ZVqPGB57Rh3HCBsuUKsqI1I3liuN7o7P05kc=
  - secure: UoTc2R1pw6IAzshPFBpn2nQfwfoCtO/e7kTk2yr6WEOH3znWgSULibFw8pe6updsd+byyxSrFFZXk7H5b5qY8lWiWkOm3L5o9Aj2/h2+m2ayo7HeeXMc3YiPW8guRz0wS+jTGkquA0KESyNZpruZO5BJ7lT8iylNiaFhdTYUZHXkvZbdNsmQB+ggM2+TYMQQOQ3ncUdmwZUUkRGxeVHYC2/nhDMRxvv8gZ2GD9CkUW0/Y/zVvjmm/fObAPpJk/XU1sdOs3KDqbnDRswpcZ/MPAsTS8seVXUwEgPnqUGV8E1y31CpXtE4jOyFASKyt9VcSyI8mMjEVo62JwpLWbVs//Bh/40bavfsnU1zoRGpm9gF9X3Mgb27Ua1YWzBmrrlrzHlZD8HImvYB+nZ9hpbrnX4f8H4W6arJAqcw8RKOagrXEgyUUCvXbK0HtbsfFkSjeiO3/zQo6MgaJ906o978Ws2LkOlqEasOPFhBgzPMCO7NWsHIWMCnuK1/wkp7BrhMKmnOgOR6M6z2esBOsYOgXOhzSsno4FZY6tXYGo9V+oicVBhSsulSpT/wfIablc0kSc0fGlWxEVqM2k7zP28Q4aY0L9PAERjCz1oqWwMUdVP01e4fAekHhjwwJsmnlEqOGZ4jRY4ClGl85ldtynwXyafvd7i2jSujXXtMY2TK7/0=
  - secure: "jjbxZWTTv5yTskdOohgP/iJa078aVc++zy+iGA6geYuQm5cd6JOWdbK9bBTGctpBanoNxjQyExIEyo9AXbUHunVEOxAadmLmbNSi8+yiza9GSCPCwSJ/hXG8IqtPH5aWrZl5RxS4xBK4aDCWa7T6Gt5D5FXtRn+3CYs8uHu0q86JDyO9sV0dtJuv8YPYjB+tRvfwRsL1tfyQtiZCvPTknFIo0R/hQJUzY+9G0+sKtM1DzDYg7UJMaI0k9IL6NhucwEDnCaOiSCt9Aw8Owbp29lCnBzoR8G8yjzy0RAA79XoZ9exeMokRBvMir1BBSIkNM5x/K9y1oe/M1hz7bXcHH35CQT4RYHkJKGf9LYbaddbBW1sHXiVLAs6Oee3bQk7uU1EQ/8gVRJwtEuIqxYPcQx6ZT1/SPMu8sSj+VbD1CoaLM5G8SF6SQdyx03U8LjrL8aKv/j0eS4yoMtX21R+nXHcm2je3Cb7HkcZZYmX55Moxs7QfQfbJTivA/xlzlHPtJN/acDNDwS/J08HRWk9Joxr0DU/uK3b8EE06oGWveajV2cWke+r6nxpfKCYTtWEo/8ilMN9C5r3I0QE7sIQx37eD/EIStfy2nJHaPTB/j6EysvHhWPgQe3aT21AKxGbnWkryHyv36iqqohi96uAkQedIo0Xyp4spIyXOJ5ap9+M="
  - secure: "wQPlvQzrKmVsUZ5+kLBiI111Rx+pROSPP3dWFVr4bptI3Dxi1ACQhdz0EpRaHSr8KvWrrou8nF33V+BAfdPKfA9vkJ7v6gHbBb/FkoYYJGP+gbordVe5hJ0E1D1BmjFxde00YjXmGb3XWJDdJUJHQb9rvybe0mlSy4uldoW2rhUQrrvp7VU47CkB6GZk37M2m3j2FxWWcZ4/F/IzDEmJxXkyNhMNHEn50y6AU9fj5fzzixA2TQqGBE20oZBVtCCeoLAxPrFNqjely6+3dGS859Sq0Q13nF/Ue5ho9Kb5Qc2vAptIYpZmz1iXarBfaoQin99JnIhQUpnbxH5jknnEnBxqee2+LitkbCUNFV3QfxI9MpYG30BWjFYOEi9jdHUEeolW2eXmE7r/G4RAIdaLtnqXa0Vq9eN5o2XJ+kqIZl5hzEjEeEOQvMMA/2C4I3y8b4P8Qx3PvNPeFFsgZokuMk+R7y+fopmwny62IMwUb+HcQPpyjFOcMKkbvBSIH4BhvqdY0gnpgR27ETrOgPuWpvtyUEMRKH0eY2k3gkyYM+kDXoM9kiG5gHyF8HPAwQEs+UR4nQf3e5HE/8FlPpTmZ2gHpzTibpZGCP4FwMGqpk2rpBp4iPPGR4k3t4O0WOBWlU6rfS8yoIPqAD4mbE9VA/c1TUAf0nyei4VEdmpvy7o="
